const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert=require('node:assert/strict');
const base=process.argv[2] || 'http://localhost:8080';
const recording=Buffer.alloc(44+46*8000*2);recording.write('RIFF',0);recording.writeUInt32LE(recording.length-8,4);recording.write('WAVEfmt ',8);recording.writeUInt32LE(16,16);recording.writeUInt16LE(1,20);recording.writeUInt16LE(1,22);recording.writeUInt32LE(8000,24);recording.writeUInt32LE(16000,28);recording.writeUInt16LE(2,32);recording.writeUInt16LE(16,34);recording.write('data',36);recording.writeUInt32LE(recording.length-44,40);
const langs=[['tel','Telugu'],['hin','Hindi'],['tam','Tamil'],['eng','English'],['','Unknown']];
const channels=langs.flatMap(([code,name])=>Array.from({length:8},(_,i)=>({id:name+i+'.in',name:name+' News '+i,country:'IN',categories:['news'],is_nsfw:false,closed:null})));
for(const channel of channels) {
 if(!channel.id.startsWith('Unknown') && /[01]\.in$/.test(channel.id)) channel.categories=['kids','news'];
}
channels.find(c=>c.id==='Telugu1.in').country='US';
channels.find(c=>c.id==='Unknown0.in').categories=['kids'];channels.find(c=>c.id==='Unknown0.in').is_nsfw=true;
channels.find(c=>c.id==='Unknown1.in').categories=['children'];
channels.find(c=>c.id==='Unknown2.in').categories=['animation'];
for(const id of ['English2.in','English3.in','Hindi2.in','Unknown3.in']) channels.find(channel=>channel.id===id).categories=['kids'];
const streams=channels.map(c=>({channel:c.id,feed:'main',url:'https://fixture.test/'+c.id+'.m3u8',quality:'720p'}));
const feeds=channels.filter(c=>!c.id.startsWith('Unknown')).map(c=>({channel:c.id,id:'main',is_main:true,languages:[langs.find(([,name])=>c.name.startsWith(name))[0]]}));
feeds.push({channel:'Telugu0.in',id:'dubbed',is_main:false,languages:['hin']});
const ts=date=>date.toISOString().replace(/[-:TZ.]/g,'').slice(0,14)+' +0000';
const now=Date.now();const xml=`<tv><programme channel="Telugu0.in" start="${ts(new Date(now-30*60000))}" stop="${ts(new Date(now+30*60000))}"><title>Evening News &amp; Weather</title></programme><programme channel="Telugu0.in" start="${ts(new Date(now+30*60000))}" stop="${ts(new Date(now+60*60000))}"><title>Next bulletin</title></programme></tv>`;
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
 let optionalFailures=false,missingMovieMetadata=false,kidsMovieFailures=true,kidsPageFailure=true,archiveAudioFailure=true;
 const page=await browser.newPage(),errors=[],queries=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>localStorage.setItem('prismtv.hideDead','0'));
 const handler=r=>{
  const u=new URL(r.request().url());
  if(optionalFailures && /\/(feeds|languages)\.json$/.test(u.pathname))return r.fulfill({status:503,body:''});
  if(u.hostname==='iptv-org.github.io'&&u.pathname.startsWith('/api/')) {
    const resources={'channels.json':channels,'streams.json':streams,'logos.json':channels.map(c=>({channel:c.id,url:'https://fixture.test/logo.svg',format:'SVG',width:300,in_use:true})),'countries.json':[{code:'US',name:'United States',flag:'🇺🇸'},{code:'IN',name:'India',flag:'🇮🇳',languages:['eng','tel','hin','tam']}],'categories.json':[{id:'news',name:'News'}],'feeds.json':feeds,'languages.json':langs.filter(x=>x[0]).map(([code,name])=>({code,name})),'guides.json':[{channel:'Telugu0.in',site_id:'Telugu0.in',lang:'en',sources:[{url:'https://fixture.test/guide.xml',format:'XML'}]}]};
    return r.fulfill({json:resources[u.pathname.split('/').pop()] || []});
  }
  if(u.pathname==='/api/health')return r.fulfill({json:{mpv:false,relay:false}});
  if(u.pathname==='/api/scan')return r.fulfill({status:404,body:''});
  if(u.pathname==='/data/site.json')return r.fulfill({json:{public:false}});
  if(u.pathname==='/data/health.json')return r.fulfill({json:{at:now/1000,s:{[streams[0].url]:'o',[streams[8].url]:'d'}}});
  if(u.hostname==='archive.org'&&u.pathname.startsWith('/download/')&&u.pathname.endsWith('.mp3')){if(archiveAudioFailure){archiveAudioFailure=false;return r.fulfill({status:404,body:''});}const range=/bytes=(\d+)-(\d*)/.exec(r.request().headers().range||'');if(range){const start=Number(range[1]),end=Math.min(range[2]?Number(range[2]):recording.length-1,recording.length-1);return r.fulfill({status:206,contentType:'audio/wav',headers:{'accept-ranges':'bytes','content-range':`bytes ${start}-${end}/${recording.length}`},body:recording.subarray(start,end+1)});}return r.fulfill({contentType:'audio/wav',headers:{'accept-ranges':'bytes'},body:recording});}
  if(u.hostname==='archive.org'&&u.pathname==='/advancedsearch.php') {queries.push(u.searchParams.get('q'));if(u.searchParams.get('q').startsWith('collection:(feature_films OR classic_tv OR animationandcartoons)') && kidsMovieFailures){kidsMovieFailures=false;return r.fulfill({status:503,body:''});}if(u.searchParams.get('q').startsWith('collection:(classic_cartoons OR vintage_cartoons)')){const pageNumber=Number(u.searchParams.get('page')||1),size=Number(u.searchParams.get('rows')||40);if(pageNumber===2 && kidsPageFailure){kidsPageFailure=false;return r.fulfill({status:503,body:''});}if(u.searchParams.get('q').includes('title:(Slow*)'))return new Promise(resolve=>setTimeout(()=>r.fulfill({json:{response:{numFound:50,docs:[{identifier:'stale-film',title:'Stale result'}]}}}).then(resolve),300));const docs=Array.from({length:50},(_,index)=>({identifier:index===0?'film-one':'cartoon-'+index,title:index===0?'Cartoon one':'Cartoon '+index}));return r.fulfill({json:{response:{numFound:50,docs:docs.slice((pageNumber-1)*size,pageNumber*size)}}});}if(u.searchParams.get('q').includes('short_films'))return r.fulfill({json:{response:{numFound:3,docs:[{identifier:'short-one',title:'A short film',runtime:'05:12'},{identifier:'long-one',title:'A long film',runtime:'90'},{identifier:'unknown-one',title:'Unknown runtime'}]}}});return r.fulfill({json:{response:{numFound:1,docs:[{identifier:'film-one',title:'A classic film',year:1942,creator:'Source studio',runtime:'01:29:30',language:['eng'],description:'A suspense story.'}]}}});}
  if(u.hostname==='archive.org'&&u.pathname==='/metadata/film-one'&&missingMovieMetadata)return r.fulfill({json:{metadata:{title:'Metadata missing film'},files:[{name:'film.mp4',format:'MPEG4'}]}});
  if(u.hostname==='archive.org'&&u.pathname==='/metadata/film-one')return r.fulfill({json:{metadata:{title:'A classic film',year:'1942',runtime:'01:29:30',language:['eng','hin'],description:'A <b>suspense</b> story.'},files:[{name:'film.mp4',format:'MPEG4'},{name:'English.vtt'}]}});
  if(u.hostname==='fixture.test'&&u.pathname==='/guide.xml')return r.fulfill({contentType:'application/xml',body:xml});
  if(u.hostname==='fixture.test'&&u.pathname==='/logo.svg')return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100"><rect width="200" height="100" fill="#b2a5d9"/></svg>'});
  if(u.hostname==='127.0.0.1'||u.hostname==='localhost')return r.continue();
  return r.fulfill({status:404,body:''});
 };
 await page.route('**/*',handler);
 const nav=view=>page.locator(`.nav-link[data-view="${view}"]:visible`).click();
 await page.goto(base);await page.locator('#boot').waitFor({state:'hidden'});
 await page.locator('.language-discovery [data-language="tel"]').click();
 assert.equal(await page.locator('#f-language').inputValue(),'tel');assert.equal(await page.locator('#browse-grid .card').count(),8);
 assert((await page.locator('#browse-grid .card .name').allTextContents()).every(t=>t.startsWith('Telugu')));
 assert.equal(await page.locator('#browse-title').innerText(),'Telugu channels');
 await page.locator('#browse-languages [data-language="hin"]').click();assert.equal(await page.locator('#browse-grid .card').count(),8);
 await page.locator('#browse-languages [data-language="tel"]').click();
 assert.equal(await page.locator('#browse-grid .card').first().getAttribute('data-id'),'Telugu0.in');
 assert.match(await page.locator('#browse-grid .content-availability').first().innerText(),/responded recently/);
 await page.locator('#browse-grid .card[data-id="Telugu0.in"]').click();await page.locator('#programme-guide summary').click();await page.locator('#programme-guide').getByText('Now · Evening News & Weather',{exact:true}).waitFor();await page.locator('#programme-guide').getByText('Next · Next bulletin',{exact:true}).waitFor();
 await page.locator('#player-close').click();await page.locator('#player').waitFor({state:'hidden'});
 await page.locator('#browse-languages [data-language="hin"]').click();await page.locator('#browse-grid .card[data-id="Hindi0.in"]').click();await page.locator('#programme-guide summary').click();await page.locator('#programme-guide').getByText('No current programme guide is available for this channel.',{exact:true}).waitFor();await page.locator('#player-close').click();await page.locator('#player').waitFor({state:'hidden'});await nav('home');await page.locator('#rows h2',{hasText:'What’s on now'}).waitFor();
 await nav('kids');assert.equal(await page.locator('#kids-grid .card').count(),12);await page.locator('#kids-live-all').click();assert.equal(await page.locator('#kids-grid .card').count(),13);assert.equal(await page.locator('#kids-live-all').isDisabled(),true);assert.equal(await page.locator('.nav-link[data-view="kids"][aria-current="page"]').count(),2);
 await page.locator('#kids-language').selectOption('tel');assert.equal(await page.locator('#kids-grid .card').count(),2);
 await page.locator('#kids-country').selectOption('US');assert.equal(await page.locator('#kids-grid .card').count(),1);
 await page.locator('#kids-search').fill('no match');assert.equal(await page.locator('#kids-grid .card').count(),0);await page.locator('#kids-reset').click();assert.equal(await page.locator('#kids-grid .card').count(),12);await page.locator('#kids-grid [data-list-id="Telugu0.in"]').click();assert.equal(await page.locator('#kids-grid [data-list-id="Telugu0.in"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#player').isVisible(),false);
 await page.locator('#kids-movies').getByRole('button',{name:'Retry Children’s films'}).click();await page.locator('#kids-movies .mcard').first().waitFor();
 await page.locator('#kids-movies .mcard-yt').first().waitFor();assert(!(await page.locator('#kids-movies .mcard-yt .name').allTextContents()).some(name=>/Adult Swim|Rick and Morty|Family guy|Vivziepop/.test(name)));await page.locator('#kids-movies .mcard-yt').first().click();await page.locator('#lplayer').waitFor({state:'visible'});await page.locator('#lplayer-close').click();await page.locator('#lplayer').waitFor({state:'hidden'});
 const cartoons=page.locator('#kids-movies .row').filter({has:page.getByRole('heading',{name:'Classic cartoons',exact:true})});await cartoons.getByRole('button',{name:'See all',exact:true}).click();await page.locator('#kids-catalogue-grid .mcard').first().waitFor();assert.equal(await page.locator('#kids-catalogue-grid .mcard').count(),48);assert.equal(await page.locator('#kids-home').isVisible(),false);assert.equal(await page.locator('#movies').isVisible(),false);assert.equal(await page.locator('#kids-collection').inputValue(),'classics');
 await page.locator('#kids-catalogue-more').click();await page.locator('#kids-catalogue-retry').waitFor({state:'visible'});assert.equal(await page.locator('#kids-catalogue-grid .mcard').count(),48);await page.locator('#kids-catalogue-retry').click();await page.waitForFunction(()=>document.querySelectorAll('#kids-catalogue-grid .mcard').length===50);assert.equal(await page.locator('#kids-catalogue-more').isVisible(),false);
 await page.locator('#kids-film-language').selectOption('telugu');await page.locator('#kids-catalogue-count').filter({hasText:'50 titles'}).waitFor();assert(queries.some(q=>q.startsWith('collection:(classic_cartoons OR vintage_cartoons)')&&q.includes('language:(tel OR te OR Telugu)')));
 await page.locator('#kids-film-sort').selectOption('titleSorter asc');await Promise.all([page.waitForRequest(request=>request.url().includes('advancedsearch.php')&&new URL(request.url()).searchParams.get('q').includes('title:(Popeye*)')),page.locator('#kids-film-search').fill('Popeye')]);await page.waitForFunction(()=>document.querySelector('#kids-catalogue-count').textContent.includes('50 titles')&&!document.querySelector('#kids-catalogue-grid').hasAttribute('aria-busy'));assert(queries.some(q=>q.includes('title:(Popeye*)')));
 const slowResponse=page.waitForResponse(response=>response.url().includes('advancedsearch.php')&&new URL(response.url()).searchParams.get('q').includes('title:(Slow*)'));await Promise.all([page.waitForRequest(request=>request.url().includes('advancedsearch.php')&&new URL(request.url()).searchParams.get('q').includes('title:(Slow*)')),page.locator('#kids-film-search').fill('Slow')]);await page.locator('#kids-collection').selectOption('stories');await slowResponse;await page.locator('#kids-catalogue-count').filter({hasText:'Fairy tales & storybook films'}).waitFor();assert.equal(await page.locator('#kids-catalogue-grid .mcard').count(),1);assert.equal(await page.locator('#kids-catalogue-grid [data-movie="stale-film"]').count(),0);
 await page.locator('#kids-catalogue-back').click();assert.equal(await page.locator('#kids-home').isVisible(),true);assert.equal(await cartoons.getByRole('button',{name:'See all',exact:true}).evaluate(element=>element===document.activeElement),true);
 const youtubeRow=page.locator('#kids-movies .row').filter({has:page.getByRole('heading',{name:'Kids shows on YouTube',exact:true})});await youtubeRow.getByRole('button',{name:'See all',exact:true}).click();await page.locator('#kids-catalogue-grid .mcard-yt').first().waitFor();assert(await page.locator('#kids-catalogue-grid .mcard-yt').count()>40);assert.equal(await page.locator('#kids-film-language').isDisabled(),true);await page.locator('#kids-film-search').fill('Nothing matches this name');await page.locator('#kids-catalogue-count').filter({hasText:'No titles found'}).waitFor();assert.equal(await page.locator('#kids-catalogue-grid .mcard').count(),0);await page.locator('#kids-film-search').fill('WB Kids');await page.waitForFunction(()=>document.querySelectorAll('#kids-catalogue-grid .mcard').length===1);assert.equal(await page.locator('#kids-catalogue-grid .name').innerText(),'WB Kids');await page.locator('#kids-catalogue-back').click();
 await page.locator('#kids-browse-all').click();await page.locator('#kids-catalogue-count').filter({hasText:'All kids films on Archive.org'}).waitFor();assert.equal(await page.locator('#kids-collection option').count(),7);await page.evaluate(()=>{window.kidsTestRandom=Math.random;Math.random=()=>0;});await page.locator('#random-btn').click();await page.evaluate(()=>{Math.random=window.kidsTestRandom;});await page.locator('#mplayer').waitFor({state:'visible'});assert.equal(await page.locator('#player').isVisible(),false);await page.locator('#mplayer-close').click();await page.locator('#mplayer').waitFor({state:'hidden'});await page.locator('#kids-collection').selectOption('stories');await page.locator('#kids-results-title').filter({hasText:'Fairy tales'}).waitFor();await page.locator('#kids-catalogue-back').click();
 await page.locator('#kids-grid .card[data-id="Telugu0.in"]').click();assert(await page.locator('#side-list .side-meta strong').count()>0);assert((await page.locator('#side-list .side-item').evaluateAll(elements=>elements.map(element=>element.dataset.id))).every(id=>channels.some(channel=>channel.id===id && channel.categories.some(category=>['kids','children'].includes(category)) && !channel.is_nsfw)));await page.locator('#player-close').click();await page.locator('#player').waitFor({state:'hidden'});
 await cartoons.locator('.mcard[data-movie="film-one"]').click();await page.locator('#mplayer').waitFor({state:'visible'});await page.locator('#mplayer-close').click();
 await nav('home');await nav('kids');assert.equal(await cartoons.locator('.mcard').count(),40);await page.locator('#kids-language').selectOption('tel');await page.locator('#kids-country').selectOption('US');await page.evaluate(()=>{window.kidsTestRandom=Math.random;Math.random=()=>0;});await page.locator('#random-btn').click();await page.evaluate(()=>{Math.random=window.kidsTestRandom;});await page.locator('#player').waitFor({state:'visible'});assert.equal(await page.locator('#player-name').innerText(),'Telugu News 1');await page.locator('#player-close').click();await page.locator('#player').waitFor({state:'hidden'});await page.locator('#kids-reset').click();
 await nav('movies');assert.equal(await page.locator('#mb-genre').inputValue(),'all');assert.equal(await page.locator('.collection-card').count(),4);
 await page.getByRole('button',{name:'Short film discoveries Films with a listed runtime of 30 minutes or less'}).click();await page.locator('#movies-grid .mcard').waitFor();assert.equal(await page.locator('#movies-grid .mcard').count(),1);assert.match(await page.locator('#movies-grid').innerText(),/A short film/);await page.getByRole('button',{name:'Classic thrillers Mystery, suspense and film noir'}).click();assert.equal(await page.locator('#mb-genre').inputValue(),'mystery');
 await page.locator('#mb-language').selectOption('telugu');await page.locator('#movies-count').filter({hasText:'Telugu'}).waitFor();assert(queries.some(q=>q.includes('language:(tel OR te OR Telugu)')));
 await page.locator('#movies-grid .mcard').first().click();await page.locator('#movie-facts').getByText('English, Hindi',{exact:true}).waitFor();await page.locator('#movie-facts').getByText('90 min',{exact:true}).waitFor();assert.match(await page.locator('#movie-facts').innerText(),/English, Hindi/);assert.match(await page.locator('#movie-facts').innerText(),/1 subtitle file/);assert.equal(await page.locator('#mplayer-desc').innerText(),'A suspense story.');
 await page.locator('#mplayer-close').click();missingMovieMetadata=true;await page.locator('#movies-grid .mcard').first().click();await page.locator('#mplayer-title').filter({hasText:'Metadata missing film'}).waitFor();assert.equal(await page.locator('#movie-facts dd',{hasText:'Not supplied'}).count(),2);assert.equal(await page.locator('#mplayer-desc').innerText(),'No synopsis supplied by this source.');await page.locator('#mplayer-close').click();missingMovieMetadata=false;await nav('learn');assert.equal(await page.locator('.path-steps li').count(),3);
 assert.equal(await page.locator('#learn-archive-grid .archive-lesson-card').count(),6);await page.locator('#learn-archive-all').click();assert.equal(await page.locator('#learn-archive-grid .archive-lesson-card').count(),15);
 await page.locator('#learn-archive-skills [data-skill="accents"]').click();assert.equal(await page.locator('#learn-archive-grid .archive-lesson-card').count(),5);await page.locator('#learn-archive-search').fill('irish');assert.equal(await page.locator('#learn-archive-grid .archive-lesson-card').count(),1);await page.locator('#learn-archive-grid .archive-lesson-card').click();await page.locator('#archive-audio-retry').waitFor({state:'visible'});await page.locator('#archive-audio-retry').click();await page.waitForFunction(()=>document.querySelector('#archive-audio').readyState>=2);assert.equal(await page.locator('#archive-audio-text').isVisible(),false);await page.locator('#archive-audio-close').click();await page.locator('#archive-audio-player').waitFor({state:'hidden'});
 await page.locator('#learn-archive-search').fill('no matching title');assert.equal(await page.locator('#learn-archive-grid .archive-lesson-card').count(),0);await page.locator('#learn-archive-search').fill('');await page.locator('#learn-archive-skills [data-skill="listening"]').click();await page.locator('#learn-archive-grid [data-archive-lesson="fox-grapes"]').click();await page.waitForFunction(()=>document.querySelector('#archive-audio').readyState>=2);assert.match(await page.locator('#archive-audio').getAttribute('src'),/fables_01_01_aesop_64kb.mp3$/);assert.equal(await page.locator('#archive-audio-text').getAttribute('href'),'https://www.gutenberg.org/ebooks/11339');await page.locator('#archive-audio-speed').selectOption('0.75');await page.locator('#archive-audio-repeat').check();assert.equal(await page.locator('#archive-audio').evaluate(audio=>audio.playbackRate),0.75);assert.equal(await page.locator('#archive-audio').evaluate(audio=>audio.loop),true);await page.locator('#archive-audio').evaluate(audio=>{audio.pause();audio.currentTime=25;});await page.waitForFunction(()=>!document.querySelector('#archive-audio').seeking&&document.querySelector('#archive-audio').currentTime===25);await page.locator('#archive-audio-replay').click();await page.waitForFunction(()=>!document.querySelector('#archive-audio').seeking&&document.querySelector('#archive-audio').currentTime===15);
 await page.locator('#archive-audio-cast').click();await page.locator('#archive-audio-cast-panel').waitFor({state:'visible'});await page.keyboard.press('Escape');assert.equal(await page.locator('#archive-audio-player').isVisible(),true);assert.equal(await page.locator('#archive-audio-cast-panel').isVisible(),false);await page.keyboard.press('Escape');await page.locator('#archive-audio-player').waitFor({state:'hidden'});assert.equal(await page.locator('#learn-archive-grid [data-archive-lesson="fox-grapes"]').evaluate(element=>element===document.activeElement),true);assert.match(await page.locator('#learn-archive-grid [data-archive-lesson="fox-grapes"]').innerText(),/Resume listening/);
 await page.reload();await page.locator('#boot').waitFor({state:'hidden'});await nav('learn');await page.locator('#learn-archive-grid [data-archive-lesson="fox-grapes"]').click();await page.waitForFunction(()=>document.querySelector('#archive-audio').currentTime>=14);assert.equal(await page.locator('#archive-audio-speed').inputValue(),'0.75');assert.equal(await page.locator('#archive-audio-repeat').isChecked(),false);await page.locator('#archive-audio-close').click();await page.locator('#archive-audio-player').waitFor({state:'hidden'});

 const complete=page.locator('.path-complete input').first();await complete.check();assert.match(await page.locator('#learn-paths [role="status"]').innerText(),/^1 of 3/);
 await page.reload();await page.locator('#boot').waitFor({state:'hidden'});await nav('learn');assert.equal(await page.locator('.path-complete input').first().isChecked(),true);
 await page.locator('[data-path="pronunciation"]').click();assert.equal(await page.locator('.path-steps li').count(),3);assert.equal(await page.evaluate(()=>document.activeElement.dataset.path),'pronunciation');
 await page.locator('.path-course').first().click();await page.locator('#lplayer').waitFor({state:'visible'});await page.locator('#lplayer-close').click();
 for(const width of [320,375,768,1024,1440]) {
   await page.setViewportSize({width,height:900});
   for(const view of ['home','browse','movies','kids','learn']) {await nav(view);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width,view+' overflow at '+width);if(width===375 && ['movies','kids','learn','home'].includes(view))await page.screenshot({path:'/private/tmp/prismtv-content-'+view+'.png'});if(view==='learn'){await page.locator('#learn-archive-grid .archive-lesson-card').first().click();await page.waitForFunction(()=>document.querySelector('#archive-audio').readyState>=2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width,'Audio dialog overflow at '+width);if(width===375)await page.screenshot({animations:'disabled',path:'/private/tmp/prismtv-archive-audio.png'});await page.locator('#archive-audio-close').click();}if(view==='kids'){await page.locator('#kids-browse-all').click();await page.locator('#kids-catalogue-grid .mcard').first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width,'Kids grid overflow at '+width);if(width===375)await page.screenshot({path:'/private/tmp/prismtv-kids-see-all.png'});await page.locator('#kids-catalogue-back').click();}}
 }
 optionalFailures=true;const degraded=await browser.newPage();degraded.on('pageerror',e=>errors.push(e.message));await degraded.route('**/*',handler);await degraded.goto(base);await degraded.locator('#boot').waitFor({state:'hidden'});assert.equal(await degraded.locator('.language-discovery [data-language="tel"]').isDisabled(),true);await degraded.close();
 assert.deepEqual(errors,[]);await page.screenshot({path:'/private/tmp/prismtv-content-paths.png'});console.log('Content, Kids See All and Archive English audio controls, resume, retry, focus and responsive checks passed');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
